mock_wine_db = [
    {
        "id": "V-001",
        "name": "360 Merlot e Cabernet",
        "cn_name": "360梅洛赤霞珠红葡萄酒",
        "region": "Friuli, Italy",
        "grapes": "Merlot 80%, Cabernet 20%",
        "price_rmb": 238,
        "notes": "黑莓、覆盆子果酱、烤榛子香气，口感复杂持久，平衡优雅。",
        "pairing": "烤肉、腊肉、滋味饱满的炖菜",
        "serving_temp": "14-18°C",
        "decant": "0-30 min",
        "alcohol": "14.5%",
        "agent_tags": ["business_dinner", "red_meat", "premium", "structured", "complex_red"],
        "status": "in_stock"
    },
    {
        "id": "V-002",
        "name": "Syrah Seduzione",
        "cn_name": "黑鹏森林西拉红葡萄酒",
        "region": "Friuli, Italy",
        "grapes": "Syrah 100%",
        "price_rmb": 228,
        "notes": "红色水果、香料、黑胡椒香气，口感宏大圆润。",
        "pairing": "牛排、意式披萨、肉丸子",
        "serving_temp": "14-18°C",
        "decant": "0-15 min",
        "alcohol": "13.5%",
        "agent_tags": ["steak", "casual_dinner", "spicy_notes", "round_red", "party_red"],
        "status": "in_stock"
    },
    {
        "id": "V-003",
        "name": "Cabernet Sauvignon Nono Miglio DOC Venezia",
        "cn_name": "黑鹏森林赤霞珠红葡萄酒",
        "region": "Friuli, Italy",
        "grapes": "Cabernet Sauvignon 100%",
        "price_rmb": 268,
        "notes": "熟樱桃、香草、辛辣香料气息，口感浓郁复杂，顺滑持久。",
        "pairing": "烤乳鸽、番茄牛腩、陈年干酪",
        "serving_temp": "14-18°C",
        "decant": "0-10 min",
        "alcohol": "13.5%",
        "agent_tags": ["business_dinner", "aged_cheese", "structured_red", "classic_red", "savory_food"],
        "status": "in_stock"
    },
    {
        "id": "V-004",
        "name": "Nero D'Avola Sicilia DOC",
        "cn_name": "黑达沃拉红葡萄酒",
        "region": "Sicily, Italy",
        "grapes": "Nero D'Avola 100%",
        "price_rmb": 228,
        "notes": "可可、醋栗、黑樱桃与香料气息，口感浓郁且平衡，酸涩度让人着迷。",
        "pairing": "炙烤羊排、孜然烤串、卤鸭",
        "serving_temp": "14-18°C",
        "decant": "0-20 min",
        "alcohol": "13.5%",
        "agent_tags": ["bbq", "grilled_meat", "bold_red", "sicily", "evening_dinner"],
        "status": "in_stock"
    },
    {
        "id": "V-005",
        "name": "Traminer Aromatico Ibisco IGP Trevenezie",
        "cn_name": "黑鹏森林琼瑶浆白葡萄酒",
        "region": "Friuli, Italy",
        "grapes": "Traminer Aromatico 100%",
        "price_rmb": 228,
        "notes": "茉莉、荔枝、柑橘、草本香气，入口清脆平衡，回味有淡淡花果香。",
        "pairing": "鳕鱼、熏鱼、意式饺子、火腿、冷餐",
        "serving_temp": "6-8°C",
        "decant": "no_decant",
        "alcohol": "13%",
        "agent_tags": ["seafood", "cold_dishes", "aromatic_white", "fresh_white", "summer_wine"],
        "status": "in_stock"
    },
    {
        "id": "V-006",
        "name": "Sauvignon Blanc Turranio DOC",
        "cn_name": "黑鹏森林长相思葡萄酒",
        "region": "Friuli, Italy",
        "grapes": "Sauvignon Blanc 100%",
        "price_rmb": 238,
        "notes": "甜瓜、桃子、胡椒叶、草本香气，干爽果酸持久，复杂优雅。",
        "pairing": "芦笋、草本风味沙拉、淡水鱼",
        "serving_temp": "8-10°C",
        "decant": "no_decant",
        "alcohol": "13%",
        "agent_tags": ["salad", "freshwater_fish", "herbal_white", "dry_white", "lunch_wine"],
        "status": "in_stock"
    },
    {
        "id": "V-007",
        "name": "Soandre Verduzzo Passito DOC",
        "cn_name": "索安德维多佐甜白",
        "region": "Friuli, Italy",
        "grapes": "Verduzzo 100%",
        "price_rmb": 268,
        "notes": "杏仁香、香草、热带水果气息，口感精致顺滑，甜度均衡优雅。",
        "pairing": "冥想酒、坚果、水果蛋糕",
        "serving_temp": "12-16°C",
        "decant": "no_decant",
        "alcohol": "14%",
        "agent_tags": ["dessert", "sweet_white", "after_dinner", "gift_option", "meditation_wine"],
        "status": "in_stock"
    }
]
